#!/usr/bin/env python3
"""Render DejaVu Sans Mono Bold into an 8x16 bitmap font (ASCII 32..126,
plus 127 = degree sign) and emit C. DejaVu fonts: Bitstream Vera license."""
import sys
from PIL import Image, ImageDraw, ImageFont

W, H = 8, 16
font = ImageFont.truetype(sys.argv[1], 15)
glyphs = [chr(c) for c in range(32, 127)] + ["°"]
out = ["/* Generated by tools/genfont.py from DejaVu Sans Mono Bold (Bitstream Vera license). */",
       "#include <stdint.h>", "",
       "/* 96 glyphs (ASCII 32..126, 127 = degree), 16 rows of 8 bits, MSB = left pixel. */",
       "const uint8_t font8x16[96][16] = {"]
preview = []
for ch in glyphs:
    img = Image.new("L", (W, H), 0)
    d = ImageDraw.Draw(img)
    l, t, r, b = d.textbbox((0, 0), ch, font=font)
    x = (W - (r - l)) // 2 - l
    d.text((x, -1), ch, font=font, fill=255)
    rows = []
    for y in range(H):
        v = 0
        for xx in range(W):
            if img.getpixel((xx, y)) > 110:
                v |= 0x80 >> xx
        rows.append(v)
    out.append("    { " + ", ".join(f"0x{v:02x}" for v in rows) + " }, /* " +
               ("'\\\\'" if ch == "\\" else "deg" if ch == "°" else repr(ch).replace("*/", "* /")) + " */")
    if ch in "0123456789%C.-ABhe:":
        preview.append((ch, ["".join("#" if v & (0x80 >> i) else "." for i in range(8)) for v in rows]))
out.append("};")
open(sys.argv[2], "w").write("\n".join(out) + "\n")
for i in range(0, len(preview), 10):
    chunk = preview[i:i+10]
    for y in range(H):
        print("  ".join(g[1][y] for g in chunk))
    print()
